config/routes.rb
Rails.application.routes.draw do

  resources :tools

end

app/models/tool.rb
class Tool < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
    @tools = Tool.all
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save
      redirect_to tool_path(@tool)
    else
      render :new
    end
  end

  def show
    @tool = Tool.find(params[:id])
  end

  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])
    @tool.update(tool_params)

    flash.notice = "Tool '#{@tool.name}' Updated!"

    redirect_to tool_path(@tool)
  end

  def destroy
    @tool = Tool.find(params[:id])
    @tool.destroy

    redirect_to @tools
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :quantity, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tools/_form.html.erb
<%= form_for(@tool) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :quantity %>
  <%= f.number_field :quantity %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>
<% end %>

app/views/tools/edit.html.erb
<h1>Edit Tool</h1>

<%= render partial: 'form' %>

app/views/tools/index.html.erb
<% @tools.each do |tool| %>
  <%= "Name: #{tool.name}" %> - <%= "Quantity: #{tool.quantity}" %> - <%= "Price: #{tool.price}" %>
  <%= link_to "Edit", edit_tool_path(tool.id) %>
  <%= link_to "Delete", tool_path(tool.id), method: :delete %>
  <br><br>
<% end %>

<%= link_to "Create New Tool!", new_tool_path %>

app/views/tools/new.html.erb
<h1> Create New Tool</h1>

<%= render partial: 'form' %>

app/views/tools/show.html.erb
<h1 class="tool_info"> <%= @tool.name %></h1>
<p>
  <%= @tool.quantity %>
</p>
<p>
  <%= @tool.price %>
</p>